<?php

namespace App\Helper;

class Country
{
    public static function getAll()
    {
            $countries = [
                1 => ["code" => "AW", "name" => "Aruba"],
                2 => ["code" => "AF", "name" => "Afghanistan"],
                3 => ["code" => "AO", "name" => "Angola"],
                4 => ["code" => "AI", "name" => "Anguilla"],
                5 => ["code" => "AX", "name" => "Åland Islands"],
                6 => ["code" => "AL", "name" => "Albania"],
                7 => ["code" => "AD", "name" => "Andorra"],
                8 => ["code" => "AE", "name" => "United Arab Emirates"],
                9 => ["code" => "AR", "name" => "Argentina"],
                10 => ["code" => "AM", "name" => "Armenia"],
                11 => ["code" => "AS", "name" => "American Samoa"],
                12 => ["code" => "AQ", "name" => "Antarctica"],
                13 => ["code" => "TF", "name" => "French Southern Territories"],
                14 => ["code" => "AG", "name" => "Antigua and Barbuda"],
                15 => ["code" => "AU", "name" => "Australia"],
                16 => ["code" => "AT", "name" => "Austria"],
                17 => ["code" => "AZ", "name" => "Azerbaijan"],
                18 => ["code" => "BI", "name" => "Burundi"],
                19 => ["code" => "BE", "name" => "Belgium"],
                20 => ["code" => "BJ", "name" => "Benin"],
                21 => ["code" => "BQ", "name" => "Bonaire, Sint Eustatius and Saba"],
                22 => ["code" => "BF", "name" => "Burkina Faso"],
                23 => ["code" => "BD", "name" => "Bangladesh"],
                24 => ["code" => "BG", "name" => "Bulgaria"],
                25 => ["code" => "BH", "name" => "Bahrain"],
                26 => ["code" => "BS", "name" => "Bahamas"],
                27 => ["code" => "BA", "name" => "Bosnia and Herzegovina"],
                28 => ["code" => "BL", "name" => "Saint Barthélemy"],
                29 => ["code" => "BY", "name" => "Belarus"],
                30 => ["code" => "BZ", "name" => "Belize"],
                31 => ["code" => "BM", "name" => "Bermuda"],
                32 => ["code" => "BO", "name" => "Bolivia (Plurinational State of)"],
                33 => ["code" => "BR", "name" => "Brazil"],
                34 => ["code" => "BB", "name" => "Barbados"],
                35 => ["code" => "BN", "name" => "Brunei Darussalam"],
                36 => ["code" => "BT", "name" => "Bhutan"],
                37 => ["code" => "BV", "name" => "Bouvet Island"],
                38 => ["code" => "BW", "name" => "Botswana"],
                39 => ["code" => "CF", "name" => "Central African Republic"],
                40 => ["code" => "CA", "name" => "Canada"],
                41 => ["code" => "CC", "name" => "Cocos (Keeling) Islands"],
                42 => ["code" => "CH", "name" => "Switzerland"],
                43 => ["code" => "CL", "name" => "Chile"],
                44 => ["code" => "CN", "name" => "China"],
                45 => ["code" => "CI", "name" => "Côte d'Ivoire"],
                46 => ["code" => "CM", "name" => "Cameroon"],
                47 => ["code" => "CD", "name" => "Congo, Democratic Republic of the"],
                48 => ["code" => "CG", "name" => "Congo"],
                49 => ["code" => "CK", "name" => "Cook Islands"],
                50 => ["code" => "CO", "name" => "Colombia"],
                51 => ["code" => "KM", "name" => "Comoros"],
                52 => ["code" => "CV", "name" => "Cabo Verde"],
                53 => ["code" => "CR", "name" => "Costa Rica"],
                54 => ["code" => "CU", "name" => "Cuba"],
                55 => ["code" => "CW", "name" => "Curaçao"],
                56 => ["code" => "CX", "name" => "Christmas Island"],
                57 => ["code" => "KY", "name" => "Cayman Islands"],
                58 => ["code" => "CY", "name" => "Cyprus"],
                59 => ["code" => "CZ", "name" => "Czechia"],
                60 => ["code" => "DE", "name" => "Germany"],
                61 => ["code" => "DJ", "name" => "Djibouti"],
                62 => ["code" => "DM", "name" => "Dominica"],
                63 => ["code" => "DK", "name" => "Denmark"],
                64 => ["code" => "DO", "name" => "Dominican Republic"],
                65 => ["code" => "DZ", "name" => "Algeria"],
                66 => ["code" => "EC", "name" => "Ecuador"],
                67 => ["code" => "EG", "name" => "Egypt"],
                68 => ["code" => "ER", "name" => "Eritrea"],
                69 => ["code" => "EH", "name" => "Western Sahara"],
                70 => ["code" => "ES", "name" => "Spain"],
                71 => ["code" => "EE", "name" => "Estonia"],
                72 => ["code" => "ET", "name" => "Ethiopia"],
                73 => ["code" => "FI", "name" => "Finland"],
                74 => ["code" => "FJ", "name" => "Fiji"],
                75 => ["code" => "FK", "name" => "Falkland Islands (Malvinas)"],
                76 => ["code" => "FR", "name" => "France"],
                77 => ["code" => "FO", "name" => "Faroe Islands"],
                78 => ["code" => "FM", "name" => "Micronesia (Federated States of)"],
                79 => ["code" => "GA", "name" => "Gabon"],
                80 => ["code" => "GB", "name" => "United Kingdom"],
                81 => ["code" => "GE", "name" => "Georgia"],
                82 => ["code" => "GG", "name" => "Guernsey"],
                83 => ["code" => "GH", "name" => "Ghana"],
                84 => ["code" => "GI", "name" => "Gibraltar"],
                85 => ["code" => "GN", "name" => "Guinea"],
                86 => ["code" => "GP", "name" => "Guadeloupe"],
                87 => ["code" => "GM", "name" => "Gambia"],
                88 => ["code" => "GW", "name" => "Guinea-Bissau"],
                89 => ["code" => "GQ", "name" => "Equatorial Guinea"],
                90 => ["code" => "GR", "name" => "Greece"],
                91 => ["code" => "GD", "name" => "Grenada"],
                92 => ["code" => "GL", "name" => "Greenland"],
                93 => ["code" => "GT", "name" => "Guatemala"],
                94 => ["code" => "GF", "name" => "French Guiana"],
                95 => ["code" => "GU", "name" => "Guam"],
                96 => ["code" => "GY", "name" => "Guyana"],
                97 => ["code" => "HK", "name" => "Hong Kong"],
                98 => ["code" => "HM", "name" => "Heard Island and McDonald Islands"],
                99 => ["code" => "HN", "name" => "Honduras"],
                100 => ["code" => "HR", "name" => "Croatia"],
                101 => ["code" => "HT", "name" => "Haiti"],
                102 => ["code" => "HU", "name" => "Hungary"],
                103 => ["code" => "ID", "name" => "Indonesia"],
                104 => ["code" => "IM", "name" => "Isle of Man"],
                105 => ["code" => "IN", "name" => "India"],
                106 => ["code" => "IO", "name" => "British Indian Ocean Territory"],
                107 => ["code" => "IE", "name" => "Ireland"],
                108 => ["code" => "IR", "name" => "Iran (Islamic Republic of)"],
                109 => ["code" => "IQ", "name" => "Iraq"],
                110 => ["code" => "IS", "name" => "Iceland"],
                111 => ["code" => "IL", "name" => "Israel"],
                112 => ["code" => "IT", "name" => "Italy"],
                113 => ["code" => "JM", "name" => "Jamaica"],
                114 => ["code" => "JE", "name" => "Jersey"],
                115 => ["code" => "JO", "name" => "Jordan"],
                116 => ["code" => "JP", "name" => "Japan"],
                117 => ["code" => "KZ", "name" => "Kazakhstan"],
                118 => ["code" => "KE", "name" => "Kenya"],
                119 => ["code" => "KG", "name" => "Kyrgyzstan"],
                120 => ["code" => "KH", "name" => "Cambodia"],
                121 => ["code" => "KI", "name" => "Kiribati"],
                122 => ["code" => "KN", "name" => "Saint Kitts and Nevis"],
                123 => ["code" => "KR", "name" => "Korea, Republic of"],
                124 => ["code" => "KW", "name" => "Kuwait"],
                125 => ["code" => "LA", "name" => "Lao People's Democratic Republic"],
                126 => ["code" => "LB", "name" => "Lebanon"],
                127 => ["code" => "LR", "name" => "Liberia"],
                128 => ["code" => "LY", "name" => "Libya"],
                129 => ["code" => "LC", "name" => "Saint Lucia"],
                130 => ["code" => "LI", "name" => "Liechtenstein"],
                131 => ["code" => "LK", "name" => "Sri Lanka"],
                132 => ["code" => "LS", "name" => "Lesotho"],
                133 => ["code" => "LT", "name" => "Lithuania"],
                134 => ["code" => "LU", "name" => "Luxembourg"],
                135 => ["code" => "LV", "name" => "Latvia"],
                136 => ["code" => "MO", "name" => "Macao"],
                137 => ["code" => "MF", "name" => "Saint Martin (French part)"],
                138 => ["code" => "MA", "name" => "Morocco"],
                139 => ["code" => "MC", "name" => "Monaco"],
                140 => ["code" => "MD", "name" => "Moldova, Republic of"],
                141 => ["code" => "MG", "name" => "Madagascar"],
                142 => ["code" => "MV", "name" => "Maldives"],
                143 => ["code" => "MX", "name" => "Mexico"],
                144 => ["code" => "MH", "name" => "Marshall Islands"],
                145 => ["code" => "MK", "name" => "North Macedonia"],
                146 => ["code" => "ML", "name" => "Mali"],
                147 => ["code" => "MT", "name" => "Malta"],
                148 => ["code" => "MM", "name" => "Myanmar"],
                149 => ["code" => "ME", "name" => "Montenegro"],
                150 => ["code" => "MN", "name" => "Mongolia"],
                151 => ["code" => "MP", "name" => "Northern Mariana Islands"],
                152 => ["code" => "MZ", "name" => "Mozambique"],
                153 => ["code" => "MR", "name" => "Mauritania"],
                154 => ["code" => "MS", "name" => "Montserrat"],
                155 => ["code" => "MQ", "name" => "Martinique"],
                156 => ["code" => "MU", "name" => "Mauritius"],
                157 => ["code" => "MW", "name" => "Malawi"],
                158 => ["code" => "MY", "name" => "Malaysia"],
                159 => ["code" => "YT", "name" => "Mayotte"],
                160 => ["code" => "NA", "name" => "Namibia"],
                161 => ["code" => "NC", "name" => "New Caledonia"],
                162 => ["code" => "NE", "name" => "Niger"],
                163 => ["code" => "NF", "name" => "Norfolk Island"],
                164 => ["code" => "NG", "name" => "Nigeria"],
                165 => ["code" => "NI", "name" => "Nicaragua"],
                166 => ["code" => "NU", "name" => "Niue"],
                167 => ["code" => "NL", "name" => "Netherlands"],
                168 => ["code" => "NO", "name" => "Norway"],
                169 => ["code" => "NP", "name" => "Nepal"],
                170 => ["code" => "NR", "name" => "Nauru"],
                171 => ["code" => "NZ", "name" => "New Zealand"],
                172 => ["code" => "OM", "name" => "Oman"],
                173 => ["code" => "PK", "name" => "Pakistan"],
                174 => ["code" => "PA", "name" => "Panama"],
                175 => ["code" => "PN", "name" => "Pitcairn"],
                176 => ["code" => "PE", "name" => "Peru"],
                177 => ["code" => "PH", "name" => "Philippines"],
                178 => ["code" => "PW", "name" => "Palau"],
                179 => ["code" => "PG", "name" => "Papua New Guinea"],
                180 => ["code" => "PL", "name" => "Poland"],
                181 => ["code" => "PR", "name" => "Puerto Rico"],
                182 => ["code" => "KP", "name" => "Korea (Democratic People's Republic of)"],
                183 => ["code" => "PT", "name" => "Portugal"],
                184 => ["code" => "PY", "name" => "Paraguay"],
                185 => ["code" => "PS", "name" => "Palestine, State of"],
                186 => ["code" => "PF", "name" => "French Polynesia"],
                187 => ["code" => "QA", "name" => "Qatar"],
                188 => ["code" => "RE", "name" => "Réunion"],
                189 => ["code" => "RO", "name" => "Romania"],
                190 => ["code" => "RU", "name" => "Russian Federation"],
                191 => ["code" => "RW", "name" => "Rwanda"],
                192 => ["code" => "SA", "name" => "Saudi Arabia"],
                193 => ["code" => "SD", "name" => "Sudan"],
                194 => ["code" => "SN", "name" => "Senegal"],
                195 => ["code" => "SG", "name" => "Singapore"],
                196 => ["code" => "GS", "name" => "South Georgia and the South Sandwich Islands"],
                197 => ["code" => "SH", "name" => "Saint Helena, Ascension and Tristan da Cunha"],
                198 => ["code" => "SJ", "name" => "Svalbard and Jan Mayen"],
                199 => ["code" => "SB", "name" => "Solomon Islands"],
                200 => ["code" => "SL", "name" => "Sierra Leone"],
                201 => ["code" => "SV", "name" => "El Salvador"],
                202 => ["code" => "SM", "name" => "San Marino"],
                203 => ["code" => "SO", "name" => "Somalia"],
                204 => ["code" => "PM", "name" => "Saint Pierre and Miquelon"],
                205 => ["code" => "RS", "name" => "Serbia"],
                206 => ["code" => "SS", "name" => "South Sudan"],
                207 => ["code" => "ST", "name" => "Sao Tome and Principe"],
                208 => ["code" => "SR", "name" => "Suriname"],
                209 => ["code" => "SK", "name" => "Slovakia"],
                210 => ["code" => "SI", "name" => "Slovenia"],
                211 => ["code" => "SE", "name" => "Sweden"],
                212 => ["code" => "SZ", "name" => "Eswatini"],
                213 => ["code" => "SX", "name" => "Sint Maarten (Dutch part)"],
                214 => ["code" => "SC", "name" => "Seychelles"],
                215 => ["code" => "SY", "name" => "Syrian Arab Republic"],
                216 => ["code" => "TC", "name" => "Turks and Caicos Islands"],
                217 => ["code" => "TD", "name" => "Chad"],
                218 => ["code" => "TG", "name" => "Togo"],
                219 => ["code" => "TH", "name" => "Thailand"],
                220 => ["code" => "TJ", "name" => "Tajikistan"],
                221 => ["code" => "TK", "name" => "Tokelau"],
                222 => ["code" => "TM", "name" => "Turkmenistan"],
                223 => ["code" => "TL", "name" => "Timor-Leste"],
                224 => ["code" => "TO", "name" => "Tonga"],
                225 => ["code" => "TT", "name" => "Trinidad and Tobago"],
                226 => ["code" => "TN", "name" => "Tunisia"],
                227 => ["code" => "TR", "name" => "Türkiye"],
                228 => ["code" => "TV", "name" => "Tuvalu"],
                229 => ["code" => "TW", "name" => "Taiwan, Province of China"],
                230 => ["code" => "TZ", "name" => "Tanzania, United Republic of"],
                231 => ["code" => "UG", "name" => "Uganda"],
                232 => ["code" => "UA", "name" => "Ukraine"],
                233 => ["code" => "UM", "name" => "United States Minor Outlying Islands"],
                234 => ["code" => "UY", "name" => "Uruguay"],
                235 => ["code" => "US", "name" => "United States"],
                236 => ["code" => "UZ", "name" => "Uzbekistan"],
                237 => ["code" => "VA", "name" => "Holy See"],
                238 => ["code" => "VC", "name" => "Saint Vincent and the Grenadines"],
                239 => ["code" => "VE", "name" => "Venezuela (Bolivarian Republic of)"],
                240 => ["code" => "VG", "name" => "Virgin Islands (British)"],
                241 => ["code" => "VI", "name" => "Virgin Islands (U.S.)"],
                242 => ["code" => "VN", "name" => "Viet Nam"],
                243 => ["code" => "VU", "name" => "Vanuatu"],
                244 => ["code" => "WF", "name" => "Wallis and Futuna"],
                245 => ["code" => "WS", "name" => "Samoa"],
                246 => ["code" => "YE", "name" => "Yemen"],
                247 => ["code" => "ZA", "name" => "South Africa"],
                248 => ["code" => "ZM", "name" => "Zambia"],
                249 => ["code" => "ZW", "name" => "Zimbabwe"],
            ];

        return $countries;
    }

    public static function getNameByCode($code)
    {
        $countries = self::getAll();
        foreach ($countries as $key => $country) {
            if ($country['code'] === strtoupper($code)) {
                return $country['name'];
            }
        }
        return null;
    }
}
