<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Genprod extends Model
{
    protected $table = 'genprod';
    protected $primaryKey = 'idprod';
    public $timestamps = false;

    protected $fillable = [
        'idfirma',
        'clasa',
        'grupa',
        'art',
        'depart',
        'desc1',
        'desc2',
        'um',
        'upc',
        'tax1',
        'tax2',
        'tax3',
        'tax4',
        'tax5',
        'serviciu',
        'multum',
        'echivstoc',
        'producator',
        'taraproducator',
        'furnizor1',
        'furnizor2',
        'furnizor3',
        'contstoc',
        'contvenit',
        'contchelt',
        'denechiv1',
        'denechiv2',
        'prodechivgrupa',
        'prodechivart',
        'valuta',
        'eticheta',
        'dataultcost',
        'pretum',
        'stdcost',
        'prodser',
        'prodlot',
        'prodkit',
        'medicament',
        'pacbox',
        'pacvol',
        'paccant',
        'pacdim',
        'pacdesc',
        'imag',
        'tip',
        'critic',
        'ambalare',
        'activ',
        'imagine',
        'data',
        'compid',
        'durata1',
        'durata2',
        'durata3',
        'durata4',
        'durata5',
        'nrluni',
        'offpeak',
        'discprod',
        'discserv',
        'comefect',
        'comvanz',
        'discgrp',
        'codmicros',
        'intern',
        'webitem',
        'nodiscount',
        'summary',
        'sex',
        'bookable',
        'categorie',
        'joining',
        'daily',
        'avans',
        'cuplu',
        'clshare',
        'nrb',
        'nrmaxperspezi',
        'bar',
        'voucher',
        'card',
        'rata',
        'combar',
        'combuc',
        'nrzile',
        'prosop',
        'btnnp',
        'artminca',
        'puncteb',
        'summaryl2',
        'desc1l2',
        'info1',
        'info1l2',
        'info2',
        'info2l2',
        'info3',
        'info3l2',
        'info4',
        'info4l2',
        'pretvar',
        'iceabn',
        'duobooking',
        'abnsec',
        'abnwe',
        'abnsed',
        'guestentrance',
        'twl',
        'cod_vama',
        'combuc2',
        'fourhands',
        'activdetcard',
        'websale'
    ];

    public function pret()
    {
        // Multi-column relationship workaround: match clasa, grupa, art
        return $this->hasMany(Pret::class, 'art', 'art')
            ->whereColumn('grupa', 'grupa')
            ->whereColumn('clasa', 'clasa');
    }
}
